- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  tags: ['base']

# - name: GatherFacts
#   vars:
#     fetch_hosts: true
#   include_role:
#     name: base
#     tasks_from: gatherfact

- name: Update etc/hosts
  ansible.builtin.lineinfile:
    dest: "/etc/hosts"
    regexp: "{{ item }}$"
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}    {{ item }}"
    backup: true
    state: present
  tags: ['base', 'hosts']
  with_items: "{{ groups['nodes'] }}"

- name: Update service domains to etc/hosts
  become: true
  vars:
    random_host: "{{ RESOURCE_PREFIX }}{{ groups['nodes'] | length | random(start=1) }}"
  ansible.builtin.lineinfile:
    dest: "/etc/hosts"
    regexp: "{{ item.value }}$"
    line: "{{ K8S_HA_VIP }}   {{ item.value }}"
    # line: "{{ hostvars[random_host].ansible_host }}    {{ K8S_HA_VIP }}"
    state: present
  tags: ['base', 'hosts']
  with_dict: "{{ DOMAINS }}"

- name: Add Kube-ApiServer domain to etc/hosts
  vars:
    localonly: false
  ansible.builtin.include_role:
    name: base
    tasks_from: hosts-k8s-api
