- name: set hostname
  tags: ['base']
  hostname:
    name: "{{ inventory_hostname }}"

- name: update etc/hosts
  tags: ['base']
  lineinfile:
    dest: "/etc/hosts"
    regexp: "\t{{ item }}$"
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}\t{{ item }}"
    backup: true
    state: present
  ignore_errors: true
  with_items: "{{ groups['nodes'] }}"

- name: update local etc/hosts
  tags: ['base', 'etchosts']
  lineinfile:
    dest: "/etc/hosts"
    regexp: "\t{{ item }}$"
    line: "{{ hostvars[item].ansible_host }}\t{{ item }}"
    state: present
  ignore_errors: true
  delegate_to: localhost
  with_items: "{{ groups['nodes'] }}"
  when: inventory_hostname == groups['nodes'][0]