- name: Set hostname
  ansibl.builtin.hostname:
    name: "{{ inventory_hostname }}"
  tags: ['base']

- name: Update etc/hosts
  ansibl.builtin.lineinfile:
    dest: "/etc/hosts"
    regexp: "{{ item }}$"
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}    {{ item }}"
    backup: true
    state: present
  tags: ['base']
  with_items: "{{ groups['nodes'] }}"
