- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"
  tags: ['base']

- name: GatherFacts
  vars:
    fetch_hosts: true
  include_role:
    name: base
    tasks_from: gatherfact

- name: Update etc/hosts
  ansible.builtin.lineinfile:
    dest: "/etc/hosts"
    regexp: "{{ item }}$"
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}    {{ item }}"
    backup: true
    state: present
  tags: ['base']
  with_items: "{{ groups['nodes'] }}"

- name: Update service domains to etc/hosts
  become: true
  vars:
    random_host: "{{ RESOURCE_PREFIX }}{{ groups['nodes'] | length | random(start=1) }}"
  ansible.builtin.lineinfile:
    dest: "/etc/hosts"
    regexp: "{{ item.value }}$"
    line: "{{ hostvars[random_host].ansible_host }}    {{ item.value }}"
    state: present
  tags: ['base']
  with_dict: "{{ DOMAINS }}"
