- name: Check if reboot required
  become: true
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot now
  become: true
  reboot:
    reboot_timeout: 300
  when: reboot_required_file.stat.exists == true