- name: Set sshIncludeDir
  ansible.builtin.set_fact: sshIncludeDir="~/.ssh/config.d" localUser="{{ lookup('env', 'USER') }}"
  tags: ['local-ssh']

- name: Set keyPath
  ansible.builtin.set_fact: keyPath="../terraform/{{ RESOURCE_PREFIX }}.pem"
  tags: ['local-ssh']

- name: Local - Copy server private key to ~/.ssh
  tags: ['local-ssh']
  become_user: "{{ localUser }}"
  ansible.builtin.copy:
    src: "{{ keyPath }}"
    dest: "~/.ssh/"
    mode: 0400
  delegate_to: localhost
  ignore_errors: true
  when: keyPath is file

- name: Local - Update ssh ~/.ssh/config.d folder
  tags: ['local-ssh']
  become_user: "{{ localUser }}"
  ansible.builtin.lineinfile:
    path: "~/.ssh/config"
    regexp: "^Include "
    line: "Include config.d/*"
    insertbefore: BOF
  delegate_to: localhost


- name: Local - Create .ssh/config.d folder
  tags: ['local-ssh']
  become_user: "{{ localUser }}"
  ansible.builtin.file:
    path: "{{ sshIncludeDir }}"
    state: directory
    mode: 0744
  delegate_to: localhost

- name: Local - Create local ssh config files
  tags: ['local-ssh']
  become_user: "{{ localUser }}"
  vars:
    on_premise: "'pi' in inventory_hostname"
  ansible.builtin.template:
    src: "templates/ssh_template.j2"
    dest: "{{ sshIncludeDir }}/{{ RESOURCE_PREFIX }}.conf"
    mode: 0744
    lstrip_blocks: true
  delegate_to: localhost
