- name: Install system updates for centos
  yum:
    name: '*'
    state: latest
    update_cache: yes
  when:
  - ansible_distribution == "CentOS"
  ignore_errors: true

- name: Install system updates for ubuntu
  apt:
    update_cache: yes
    cache_valid_time: 86400
  when:
  - ansible_distribution == "Ubuntu"