- name: Delete Content and Directory
  ansible.builtin.file:
    path: "{{ item }}"
    force: true
    state: absent
  with_items:
    - /etc/kubernetes/
    - ~/.kube
    - /var/lib/etcd
    - /var/lib/kubelet
    - /etc/cni/net.d
    - /opt/cni
    - /etc/cni
    - /var/run/flannel
    - /var/lib/containerd
