- name: CNI package
  ansible.builtin.include_role:
    name: k8s.uninstall
    tasks_from: cni0

- name: UnHold package
  vars:
    hold: false
  ansible.builtin.include_role:
    name: k8s
    tasks_from: hold-pkg-version

- name: Kubeadm
  ansible.builtin.include_role:
    name: k8s.uninstall
    tasks_from: kubeadm

- name: Package
  ansible.builtin.include_role:
    name: k8s.uninstall
    tasks_from: package

- name: Files
  ansible.builtin.include_role:
    name: k8s.uninstall
    tasks_from: config

- name: Restart service
  ansible.builtin.include_role:
    name: k8s.uninstall
    tasks_from: restart