- name: CNI package
  ansible.builtin.include_role:
    name: k8s.uninstall
    tasks_from: pi4-centos9
  when: is_centos9_pi

- name: Kubeadm
  ansible.builtin.include_role:
    name: k8s.uninstall
    tasks_from: kubeadm

- name: Package
  ansible.builtin.include_role:
    name: k8s.uninstall
    tasks_from: package

- name: Files
  ansible.builtin.include_role:
    name: k8s.uninstall
    tasks_from: config