- name: Package
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni
  tags: ['pkg']

- name: Autoremove
  ansible.builtin.command: yum autoremove -y
  when: is_cent_os
  tags: ['pkg']
