- set_fact: isAdmin="{{ inventory_hostname in groups['ceph_adm'] }}"
- set_fact: nodes="{{ groups['ceph'] | join(" ") }}"
- set_fact: lvm="/dev/nvme1n1"

- include_role:
    name: ceph
    tasks_from: stop-start.yml

- name: Upgrade all package
  include_role:
    name: base
    tasks_from: pkg-upgrade

- name: If require reboot
  ansible.builtin.include_role:
    name: base
    tasks_from: reboot.yml

- name: Bootstrap
  include_role:
    name: ceph
    tasks_from: bootstrap.yml

- name: Configure hosts
  ansible.builtin.include_role:
    name: ceph
    tasks_from: configure.yml

- name: Configure file system
  ansible.builtin.include_role:
    name: ceph
    tasks_from: fs.yml

- name: Health check
  ansible.builtin.include_role:
    name: ceph
    tasks_from: health.yml

- name: Show Info
  ansible.builtin.include_role:
    name: ceph
    tasks_from: output.yml
