
- name: get key
  ansible.builtin.shell: ceph auth get-key client.{{ CEPHFS_CLIENT }}
  register: result

- name: set clientKey
  set_fact: clientKey="{{ result.stdout }}"

- name: get fsid
  ansible.builtin.shell: cephadm shell ceph fsid | tail -n1
  register: result

- name: set fsid
  set_fact: fsid="{{ result.stdout }}"

- name: mon stat
  ansible.builtin.shell: ceph mon stat|awk '{print $(NF)}'
  register: result

- name: mon stat print
  set_fact: mon="{{ result.stdout }}"

- name: k8s csi key
  ansible.builtin.debug:
    msg: "account client.{{ CEPHFS_CLIENT }}, key {{ clientKey }}, fsid: {{ fsid }}, mon: {{ mon }}"

- name: Ceph Dashboard
  ansible.builtin.debug:
    msg: "https://{{ inventory_hostname }}:8443, {{ CEPH_USER }} / {{ CEPH_PASS }}"
