- name: Stop service
  ansible.builtin.service:
    name: ceph.target
  tags: ['stop', 'stop-ceph']
  when: "'all' not in ansible_run_tags"

# - name: Start service
#   ansible.builtin.service:
#     name: ceph.target
#   tags: ['start', 'start-ceph']
#   when: "'all' not in ansible_run_tags"