- name: HAProxy - Install package
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - haproxy
    - keepalived
    - psmisc

- name: Gather fact
  vars:
    fetch_hosts: true
  ansible.builtin.include_role:
    name: base
    tasks_from: gatherfact

- name: For HaProxy able to start (SELinux issue)
  ansible.builtin.shell: setsebool -P haproxy_connect_any=1
  when: is_centos9_pi

- name: KeepAlived - Configure
  ansible.builtin.template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    lstrip_blocks: true
    mode: 0644

- name: KeepAlived - Start
  ansible.builtin.systemd:
    name: keepalived
    enabled: true
    state: restarted
    daemon_reload: true

- name: HAProxy - Configure
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    lstrip_blocks: true
    mode: 0644

- name: HAProxy - Start
  ansible.builtin.systemd:
    name: haproxy
    enabled: true
    state: restarted
    daemon_reload: true

