- set_fact: dir="../k8s-operator/memcached-operator" img="jasoncheng/k8s-ansible-operator-memcached"

- name: make, push ansible operator to docker registry
  shell: "make docker-build docker-push IMG={{ img }} && make deploy IMG={{ img }} && kubectl apply -f config/samples/cache_v1alpha1_memcached.yaml"
  args:
    chdir: "{{ dir }}"
  register: result

- debug: msg="{{ result.stdout_lines }}"

- shell: kubectl get pods -o=name | grep memcache|sed "s/^.\{4\}//"
  register: podname
  until: podname.stdout_lines | length > 0
  retries: 10
  delay: 3
  ignore_errors: true

- debug: msg="{{ podname }}"

- wait_for: timeout=10

- name: check if memcached running
  shell: "kubectl exec {{ podname.stdout }} -- netstat -tulpn|grep memcache"
  register: result
  ignore_errors: true

- debug: msg="{{ result }}"

- name: delete deployment
  shell: "make undeploy"
  args:
    chdir: "{{ dir }}"
  register: result

- debug: msg="{{ result.stdout_lines }}"