apiVersion: v1
kind: Pod
metadata:
  name: "busybox1"
  namespace: jason
spec:
  containers:
  - image: busybox
    name: busybox
    command: [ "sleep","6000"]
  dnsConfig:
    options:
      - name: ndots
        value: "7"
