- name: Clean test resource
  ansible.builtin.shell: "kubectl delete -f {{ tmpDir }}"

- name: Clean test files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ tmpDir }}"
    - "{{ tmpImageDir }}"