# - name: Pip packages
#   ansible.builtin.pip:
#     state: latest
#     name:
#     - docker==4.4.4

# - name: Docker login
#   ansible.builtin.include_role:
#     name: docker
#     tasks_from: main

# - name: Build and push test image
#   ansible.builtin.include_role:
#     name: test.k8s.keda
#     tasks_from: image

- name: Create k8s HPA test app
  ansible.builtin.include_role:
    name: test.k8s.keda
    tasks_from: apply

# - name: Verify
#   ansible.builtin.include_role:
#     name: test.k8s.keda
#     tasks_from: verify

# - name: Test
#   ansible.builtin.include_role:
#     name: test.k8s.keda
#     tasks_from: test