- name: Set fact
  ansible.builtin.set_fact:
    action: "{{ 'present' if uninstall is not defined or not uninstall else 'absent' }}"

- name: Modprobe rbd
  ansible.builtin.command: modprobe rbd
  when: not is_centos7_pi

- name: Modprobe ceph
  ansible.builtin.command: modprobe ceph
  when: not is_centos7_pi

- name: If require reboot
  ansible.builtin.include_role:
    name: base
    tasks_from: reboot

- name: Add repo
  kubernetes.core.helm_repository:
    name: rook-release
    repo_url: https://charts.rook.io/release
  when:
    - inventory_hostname in groups['k8sM']
    - action != 'absent'

- name: "Do {{ action }} rook-ceph operator"
  when: inventory_hostname in groups['k8sM']
  kubernetes.core.helm:
    create_namespace: true
    release_namespace: rook-ceph
    chart_ref: rook-release/rook-ceph
    update_repo_cache: true
    release_state: "{{ action }}"
    release_name: rook-ceph
    release_values:
      pspEnable: false
      monitoring:
        enabled: true
      resources: null
      csi:
        # RBD
        enableRbdDriver: true
        enableRBDSnapshotter: true
        csiRBDProvisionerResource: null
        csiRBDPluginResource: null

        # CephFS
        enableCephfsDriver: true
        enableCephfsSnapshotter: true

        # CSI
        csiNFSProvisionerResource: null
        csiNFSPluginResource: null

- name: "Do {{ action }} rook-ceph-cluster"
  when: inventory_hostname in groups['k8sM']
  kubernetes.core.helm:
    create_namespace: true
    release_namespace: rook-ceph
    chart_ref: rook-release/rook-ceph-cluster
    update_repo_cache: true
    release_state: "{{ action }}"
    release_name: rook-ceph-cluster
    release_values:
      pspEnable: false
      monitoring:
        enabled: true
      toolbox:
        enabled: true
      cephClusterSpec:
        removeOSDsIfOutAndSafeToRemove: true
        mon:
          allowMultiplePerNode: true
        mgr:
          allowMultiplePerNode: true
        dashboard:
          enabled: true
          ssl: false
        resources: null
        storage:
          useAllNodes: true
          useAllDevices: true
      cephObjectStores: null

- name: Deploy Ingress
  ansible.builtin.include_role:
    name: k8s.rook.ceph
    tasks_from: ingress
  when: action != 'absent'

- name: Fetch admin password
  ansible.builtin.shell: |
    kubectl -n rook-ceph get secret rook-ceph-dashboard-password -o jsonpath="{['data']['password']}" | base64 --decode && echo
  register: result
  until: result.rc == 0 and result.stdout != ""
  retries: 18
  delay: 10
  when: action != 'absent'

- name: Show dashboard info
  ansible.builtin.debug:
    msg:
      - "Ceph Portal: https://{{ DOMAINS['ceph'] }}"
      - "user: admin"
      - "pass: {{ result.stdout }}"
  when: action != 'absent'

- name: Enable module
  ansible.builtin.include_role:
    name: k8s.rook.ceph
    tasks_from: enableRook
  when: action != 'absent'

# sgdisk -n 1:0:+500G /dev/sda -t 1:45b0969e-9b03-4f30-b4c6-b4b80ceff106 -c 1:"ceph journal"
# sgdisk -n 2:0:+500G /dev/sda -t 2:4fbd7e29-9d25-41b8-afd0-062c0ceff05d -c 2:"ceph data"
# dd if=/dev/zero of=/dev/sda1 bs=1M count=100 oflag=direct,dsync
# dd if=/dev/zero of=/dev/sda2 bs=1M count=100 oflag=direct,dsync

# kubectl patch storageclass ceph-block -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
# kubectl patch storageclass ceph-filesystem -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'