- name: Copy join command
  become: true
  become_user: root
  ansible.builtin.copy:
    src: "{{ k8s_join_command_file }}"
    dest: "{{ k8s_join_command_file }}"
    mode: 0777

- name: Set var
  ansible.builtin.set_fact:
    cert_str: "{{ '' if not enable_k8s_ha_mode or inventory_hostname not in groups['k8sApis'] else '--control-plane' }}"

- name: Set var
  ansible.builtin.set_fact:
    join_cmd: "{{ lookup('file', k8s_join_command_file) }} {{ cert_str }}"

- name: Debug info
  ansible.builtin.debug:
    msg: "{{ join_cmd }}"

- name: Worker nodes join cluster
  become: true
  become_user: root
  ansible.builtin.command: "{{ join_cmd }}"
  register: result
  changed_when: result.rc == 0
  failed_when: result.rc != 0 and result.stderr is defined and ('is in use' not in result.stderr or 'already exists' not in result.stderr)
