- name: Prometheus - Add repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "{{ chart_prometheus }}"

# - name: Prometheus - Load Scrape Urls from additionalScrapeUrls.yml
#   ansible.builtin.include_vars:
#     dir: vars
#     files_matching: additionalScrapeUrls.yml

- name: Prometheus - Helm Value
  ansible.builtin.set_fact:
    helm_value: "{{ lookup('template', 'prometheus_values.yml') }}"

- name: Prometheus - Deploy
  kubernetes.core.helm:
    release_name: prometheus-stack
    release_namespace: "{{ prometheus_namespace }}"
    create_namespace: true
    chart_ref: prometheus-community/kube-prometheus-stack
    update_repo_cache: true
    release_values: "{{ helm_value | from_yaml }}"

- name: Prometheus helm values
  ansible.builtin.debug:
    msg:
      - "{{ helm_value | from_yaml }}"