- name: Prometheus - Load Scrape Urls from additionalScrapeUrls.yml
  ansible.builtin.include_vars:
    dir: vars
    files_matching: additionalScrapeUrls.yml

- name: Deploy blackbox
  kubernetes.core.helm:
    create_namespace: true
    release_namespace: blackbox
    chart_ref: prometheus-community/prometheus-blackbox-exporter
    update_repo_cache: true
    release_name: blackbox
    release_values:
      scrape_configs:
        - job_name: 'blackbox'
          metrics_path: /probe
          params:
            module: [http_2xx]
          static_configs:
            - targets: "{{ SCRAPE_URLS }}"
          relabel_configs:
            - source_labels: [__address__]
              target_label: __param_target
            - source_labels: [__param_target]
              target_label: instance
            - target_label: __address__
              replacement: 127.0.0.1:9115