- name: install docker
  ansible.builtin.shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh

- name: Add docker group
  ansible.builtin.group:
    name: "docker"
    state: present

- name: Add ubuntu to docker group
  ansible.builtin.user:
    name: "ubuntu"
    groups: ["docker"]
    append: yes
  ignore_errors: true
  when: OS_USER == "ubuntu"

- name: Add  {{ K8S_USER }}  to docker group
  ansible.builtin.user:
    name: "{{ K8S_USER }}"
    groups: ["docker"]
    append: yes
  ignore_errors: true
  when: K8S_USER != OS_USER
