---

- ansible.builtin.import_playbook: env.yml

- name: Kubernetes Cluster
  hosts: k8sS, k8sM
  become: true
  roles:
    - { role: k8s, tags: ['k8s', 'k8sM', 'k8sS'] }

- name: K8S - Master
  hosts: k8sM[0]
  gather_facts: true
  become_user: "{{ K8S_USER }}"
  roles:
    - { role: k8s.master, tags: ['k8s', 'k8sM'] }

- name: K8S - Slaver
  hosts: k8sS
  gather_facts: false
  become_user: "{{ K8S_USER }}"
  roles:
    - { role: k8s.slaver, tags: ['k8s', 'k8sS'] }

- name: Ingress Nginx
  hosts: k8sM
  gather_facts: false
  roles:
    - { role: k8s.ingress.nginx , tags: ['ingress-nginx'] }

- name: Deploy kube config to all nodes
  hosts: all
  gather_facts: false
  tasks:
    - name: Deploy
      ansible.builtin.include_role:
        name: k8s.slaver
        tasks_from: kube-config
  
- name: Show Info
  hosts: k8sM[0]
  gather_facts: false
  tasks:
  - name: List nodes
    ansible.builtin.include_role:
      name: k8s
      tasks_from: ls_node
