# Pi
# /boot/cmdline.txt
# cgroup_enable=memory 和 cgroup_memory=1

- name: collect service
  service_facts:
  register: services
  
- name: check if snapd exists
  set_fact: has_snapd="{{ 'snapd' in services }}"

- name: enable snapd
  ansible.builtin.systemd:
    name: snapd
    enabled: true
    state: started
  when: has_snapd

- name: create snapd symbolic link
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  when: has_snapd

- name: Create containerd config file
  ansible.builtin.file:
    path: "/etc/modules-load.d/containerd.conf"
    state: "touch"
  when:
  - groups.external is not defined or inventory_hostname not in groups['external']
  ignore_errors: true

- name: Add conf for containerd
  blockinfile:
    path: "/etc/modules-load.d/containerd.conf"
    block: |
      overlay
      br_netfilter
  when:
  - groups.external is not defined or inventory_hostname not in groups['external']
  
- name: Modprobe
  ansible.builtin.shell: |
    mobprobe overlay
    modprobe br_netfilter
  when:
  - groups.external is not defined or inventory_hostname not in groups['external']

- name: Set system configurations for k8s
  ansible.builtin.file:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    state: "touch"

- name: Add conf for containerd
  ansible.builtin.blockinfile:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    block: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply new settings
  ansible.builtin.command: sysctl --system

- name: install docker
  ansible.builtin.shell: |
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
  when: is_cent_os

- name: Pi4 - enable and start docker
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started
  when: is_cent_os and is_pie4

- name: config containerd
  ansible.builtin.shell: |
    mkdir -p /etc/containerd
    containerd config default | sudo tee /etc/containerd/config.toml
    systemctl restart containerd
  when: groups.external is not defined or inventory_hostname not in groups['external']
  ignore_errors: true

- name: Disable swap
  ansible.builtin.shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: install and configure dependencies
  ansible.builtin.shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  when: not is_cent_os

- name: RHEL import gpg key
  shell: |
    rpm --import https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  when: is_cent_os

- name: Repo for apt
  set_fact: k8s_sourcelist="/etc/apt/sources.list.d/kubernetes.list"
  when: not is_cent_os

- name: Create k8s repo file
  file:
    path: "{{ k8s_sourcelist }}"
    state: "touch"
  when: not is_cent_os

- name: RHEL add k8s repo
  yum_repository:
    name: kubernetes
    gpgcheck: yes
    repo_gpgcheck: no
    description: for kubernetes
    enabled: yes
    file: k8s_repo
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-{{ 'aarch64' if is_pie4 else 'x86_64' }}"
  when: is_cent_os

- name: Add k8s source
  ansible.builtin.blockinfile:
    path: "{{ k8s_sourcelist }}"
    block: |
      deb https://apt.kubernetes.io/ kubernetes-xenial main
  when: not is_cent_os

- name: apt update
  ansible.builtin.apt:
    update_cache: true
  when: is_ubuntu_os

- name: Install k8s
  ansible.builtin.package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl

- name: Install helm by snapd
  snap:
    name: helm
    classic: true
  when: has_snapd

- name: Install helm by using script
  ansible.builtin.shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  environment:
    VERIFY_CHECKSUM: "false"
  when: not has_snapd
  