# /boot/cmdline.txt
# cgroup_enable=memory 和 cgroup_memory=1
- name: enable snapd
  systemd:
    name: snapd
    enabled: true
    state: started

- name: create snapd symbolic link
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: Create containerd config file
  file:
    path: "/etc/modules-load.d/containerd.conf"
    state: "touch"
  when:
  - groups.external is not defined or inventory_hostname not in groups['external']
  ignore_errors: true

- name: Add conf for containerd
  blockinfile:
    path: "/etc/modules-load.d/containerd.conf"
    block: |
      overlay
      br_netfilter
  when:
  - groups.external is not defined or inventory_hostname not in groups['external']
  
- name: Modprobe
  shell: |
    mobprobe overlay
    modprobe br_netfilter
  when:
  - groups.external is not defined or inventory_hostname not in groups['external']

- name: Set system configurations for k8s
  file:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    state: "touch"

# - name: Install helm
#   shell: "snap install helm --classic"

- name: Install helm
  snap:
    name: helm
    classic: true

# - name: Init helm
#   shell: helm init --stable-repo-url=https://charts.helm.sh/stable

- name: Add conf for containerd
  blockinfile:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    block: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply new settings
  command: sysctl --system

- name: install containerd
  shell: |
    # apt-get install -y containerd acl || true
    mkdir -p /etc/containerd
    containerd config default | sudo tee /etc/containerd/config.toml
    systemctl restart containerd
  when: groups.external is not defined or inventory_hostname not in groups['external']
  register: result
  ignore_errors: true

# - name: install containerd for PI4
#   shell: |
#     curl -fsSL https://get.docker.com -o get-docker.sh
#     sh get-docker.sh
#   when: result.stat.rc != 0

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: install and configure dependencies
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  when: isCentOS == False

- name: RHEL import gpg key
  shell: |
    rpm --import https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  when: isCentOS

- set_fact: k8s_sourcelist="/etc/apt/sources.list.d/kubernetes.list"
  when: isCentOS == False

- name: Create k8s repo file
  file:
    path: "{{ k8s_sourcelist }}"
    state: "touch"
  when: isCentOS == False

- name: RHEL add k8s repo
  yum_repository:
    name: kubernetes
    gpgcheck: yes
    repo_gpgcheck: no
    description: for kubernetes
    enabled: yes
    file: k8s_repo
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
  when: isCentOS

- name: Add k8s source
  blockinfile:
    path: "{{ k8s_sourcelist }}"
    block: |
      deb https://apt.kubernetes.io/ kubernetes-xenial main
  when: isCentOS == False

# - name: Install kubernets
#   tags: ['install']
#   shell: |
#     apt-get update
#     apt-get install -y kubelet kubeadm kubectl

- name: Install k8s
  package:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
    - kubelet
    - kubeadm
    - kubectl