- name: Create containerd config file
  file:
    path: "/etc/modules-load.d/containerd.conf"
    state: "touch"
  when: inventory_hostname not in groups['external']

- name: Add conf for containerd
  blockinfile:
    path: "/etc/modules-load.d/containerd.conf"
    block: |
      overlay
      br_netfilter
  when: inventory_hostname not in groups['external']

- name: Modprobe
  shell: |
    mobprobe overlay
    modprobe br_netfilter
  when: inventory_hostname not in groups['external']

- name: Set system configurations for k8s
  file:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    state: "touch"

- name: Install helm
  community.general.snap:
    name: helm
    classic: true
  # shell: "snap install helm --classic"

- name: Add conf for containerd
  blockinfile:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    block: |
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
      net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply new settings
  command: sysctl --system

- name: install containerd
  shell: |
    apt-get install -y containerd acl
    mkdir -p /etc/containerd
    containerd config default | sudo tee /etc/containerd/config.toml
    systemctl restart containerd
  when: inventory_hostname not in groups['external']

- name: Disable swap
  shell: |
    swapoff -a
    sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: install and configure dependencies
  shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  when: centOS == false

- set_fact: k8s_sourcelist="/etc/apt/sources.list.d/kubernetes.list"

- name: Create k8s repo file
  file:
    path: "{{ k8s_sourcelist }}"
    state: "touch"
  when: centOS == false

- name: Add k8s source
  blockinfile:
    path: "{{ k8s_sourcelist }}"
    block: |
      deb https://apt.kubernetes.io/ kubernetes-xenial main
  when: centOS == false


- name: Create k8s repo file for centos
  copy:
     dest: "/etc/yum.repos.d/kubernetes.repo"
     content: |
       [kubernetes]
       name=Kubernetes
       baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
       enabled=1
       gpgcheck=0
       repo_gpgcheck=0
       gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
  when: centOS

# - name: Install kubernets
#   tags: ['install']
#   shell: |
#     apt-get update
#     apt-get install -y kubelet kubeadm kubectl
  
- name: Instal kubernetes
  package:
    state: present
    name: "{{ item }}"
  with_items:
  - kubelet
  - kubeadm
  - kubectl

- name: Disable SELinux
  shell: |
    sudo setenforce 0
    sudo sed -i --follow-symlinks 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/sysconfig/selinux